### ISSUE TITLE
Anxiously awaiting...

### ISSUE THREAD

**Issue by fdncred** [kaby76/Piggy#1]
No issue. Just wanted to say that I'm anxiously awaiting a version that mostly works so that I can try it out on [Leptonica](http://www.leptonica.com) (site my be down) and Github [code](https://github.com/DanBloomberg/leptonica).

**Comment by kaby76** [comment]
Sorry, it's not there yet. I've written a status update here: http://codinggorilla.com/?p=1664 . It's taken quite a while to get the output engine to work. I go over in the blog a little bit about how the program works. It can convert enums, but now I'm working on the patterns for methods. I'll try running the sources of Leptonica through the tool. :)

**Comment by fdncred** [comment]
Very interesting read. I'm going to download your repo and try to run your ast dumper on my code to see what happens.

Not that it matters much but I've tried using all these p/invoke generators too and haven't had a lot of success. Most recently I tried [NClang](https://github.com/atsushieno/nclang).
