### ISSUE TITLE
Output (Feature Request)

### ISSUE THREAD

**Issue by fdncred** [kaby76/Piggy#12]
Here's another item that you may want to think about. This is mainly taken from my work with NClang and it's sample app PInvokeGenerator.

Leptonica isn't a huge library but it's big enough to be an unreasonable size when putting the output all in one file. One of the things that I like about my incomplete and modified PInvokeGenerator.exe is that I can pass each .h file and each .c file and a unique .cs file is created for each.

Having DLL imports is nice, but having them organized by c source file is nicer. It also helps because if one is going to make a useable API for a C/C++ lib, one is going to have to have helper classes and such. If the pinvoke generator puts them in separate files, then it's easier to modify the library bit by bit, class by class. It's hard when everything you deal with is an IntPtr for most objects. I want to have traditional class is with properties an such.

I tried modifying the include.c and putting all the .h and .c files in there but piggy pukes.

Thanks,
Darren

**Comment by kaby76** [comment]
The code fix for this is in v1.0.9. Note: to generate a file per type, set the -o option of PiggyTool to a directory. If it's not a directory (a file), then the output will be directed to that. If -o is not set at all, then output will go to stdout.

**Comment by fdncred** [comment]
I see you've been working hard on this. Thanks for the dedication. I can't wait to try out all these new changes.

**Comment by fdncred** [comment]
Can you help me understand how to use this?

From the command line
```
>dotnet "c:\Users\username\.nuget\packages\piggy\1.0.9\build\ClangSerializer.dll" -c "ID:/Src/GitHub/Leptonica/src" "ID:/Src/GitHub/Leptonica/build/src" "ID:/Src/GitHub/Leptonica/prog" -f "C:\Users\username\Documents\Visual Studio 2017\Projects\LeptPig\LeptPig\include.c" -o "c:\Users\username\Downloads\Piggy-CommandLine"\ast.txt

>dotnet "c:\Users\username\.nuget\packages\piggy\1.0.9\build\PiggyTool.dll" -a "c:\Users\username\Downloads\Piggy-CommandLine\ast.txt" -s "c:\Users\username\Documents\Visual Studio 2017\Projects\LeptPig\LeptPig\lep.pig" -t "C:\Users\username\.nuget\packages\piggy\1.0.9\Templates" -o "c:\Users\username\Downloads\Piggy-CommandLine"
Info: Command line args System.String[]
Info: ast_file c:\Users\username\Downloads\Piggy-CommandLine\ast.txt
Info: spec_file c:\Users\username\Documents\Visual Studio 2017\Projects\LeptPig\LeptPig\lep.pig
Info: keep_file False
Info: expression
Info: output_file c:\Users\username\Downloads\Piggy-CommandLine
Info: template_directory C:\Users\username\.nuget\packages\piggy\1.0.9\Templates
SourceFile(c:\temp\generated_templates.cs[50858..50863)): CS0103 The name 'limit' does not exist in the current context
SourceFile(c:\temp\generated_templates.cs[50491..50496)): CS0103 The name 'limit' does not exist in the current context
SourceFile(c:\temp\generated_templates.cs[50989..50996)): CS0103 The name 'dllname' does not exist in the current context
SourceFile(c:\temp\generated_templates.cs[51082..51087)): CS0103 The name 'limit' does not exist in the current context
SourceFile(c:\temp\generated_templates.cs[50673..50678)): CS0103 The name 'limit' does not exist in the current context
SourceFile(c:\temp\generated_templates.cs[47955..47969)): CS0103 The name 'namespace_name' does not exist in the current context

Unhandled Exception: System.Exception: Exception of type 'System.Exception' was thrown.
   at PiggyGenerator.OutputEngine.GenerateAndCompileTemplates() in C:\Users\Kenne\Documents\Piggy3\PiggyGenerator\OutputEngine.cs:line 132
   at PiggyGenerator.OutputEngine.Run(Boolean grep_only) in C:\Users\Kenne\Documents\Piggy3\PiggyGenerator\OutputEngine.cs:line 638
   at PiggyGenerator.Piggy.RunTool(String ast_file, String spec_file, Boolean keep_file, String expression, String template_directory, String output_file) in C:\Users\Kenne\Documents\Piggy3\PiggyGenerator\Piggy.cs:line 86
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\Kenne\Documents\Piggy3\PiggyTool\Program.cs:line 64
```

From my project - what should I change here?
```xml
    <ItemGroup>
        <PackageReference Include="piggy" Version="1.0.9">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <Piggy Update="lep.pig">
            <ClangSourceFile>include.c</ClangSourceFile>
            <AstOutputFile>ast.txt</AstOutputFile>
            <ClangOptions>"ID:/Src/GitHub/Leptonica/src" "ID:/Src/GitHub/Leptonica/build/src"</ClangOptions>
        </Piggy>
    </ItemGroup>
```

**Comment by kaby76** [comment]
Make sure to pick up the latest of .pig file at https://github.com/kaby76/PiggyLeptonica/blob/master/ConsoleApp1/lep.pig , or try to mimic it. The error messages leave much to be desired. Basically the problem is that "limit" is being used in the wrong class. So, look for "${...limit...}" in patterns, and "limit = ...;" in "header" and "init" code blocks. Make sure you create a "template FoobarClangSupport : ClangSupport {}" and call FoobarClangSupport.Start down in the "application" section.

**Comment by fdncred** [comment]
I got it to generate from the new lep.pig. That's what I was missing. Definitely making progress.  Here's the latest issue.

While compiling with 1.0.9
`>obj\x64\Debug\netcoreapp2.2;g-PIX-29.cs(9,20,9,25): error CS0523: Struct member 'PIX.Value' of type 'PIX' causes a cycle in the struct layout`

g-PIX-29.cs
```cs
// This file generated by Piggy. Do not edit.
namespace Native
{
    using System;
    using System.Runtime.InteropServices;
    [StructLayout(LayoutKind.Sequential)]
    public partial struct PIX
    {
        public PIX Value;
        public PIX(PIX value)
        {
            this.Value = value;
        }
    }
}
```
g-Pix.cs
```cs
// This file generated by Piggy. Do not edit.
namespace Native
{
    using System;
    using System.Runtime.InteropServices;
    [StructLayout(LayoutKind.Sequential)]
    public partial struct Pix
    {
        public uint w;
        public uint h;
        public uint d;
        public uint spp;
        public uint wpl;
        public uint refcount;
        public int xres;
        public int yres;
        public int informat;
        public int special;
        public IntPtr text;
        public IntPtr colormap;
        public IntPtr data;
    }
}
```

**Comment by kaby76** [comment]
So, the file g-Pix.cs is generated for the   ( RecordDeclKindName="struct" Name="Pix" Attrs="definition" ... ) AST node. That looks good.

The other file, g-PIX-29.cs (which should be actually g-PIX-1.cs, another "to do") is generated for the AST node ( TypedefDecl  Name="PIX" Type="struct Pix:struct Pix" ... ). That doesn't work because, somehow, the constructor for the struct is itself PIX. As noted, there's no typedefs in C#, but you can trick the C# compiler by making a struct with one element in it--the equivalent type for the typedef. I don't see PIX in a child of that TypedefDecl, so that's puzzling. I'll put in some code to check for a circular construction.

Could you pass me your .pig file so I can find and fix this problem? Thanks.

**Comment by fdncred** [comment]
Sure. Here's my pig.
[lep.pig.txt](https://github.com/kaby76/Piggy/files/2805092/lep.pig.txt)

**Comment by fdncred** [comment]
This is kind of my use case.

I'll probably just end up renaming the `struct Pix` to `struct PIX` and then creating `partial class Pix` somewhere else, and throw away what ever is generated from `typedef struct Pix PIX;`. This way I can instantiate a `Pix()` with an `IntPtr` and `Marshal.Ptr2Structure(ptr, PIX)` to get a proper Pix object with properties.

The Leptonica API changes frequently so I want to make my changes in separate files so that I can continually piggy-fy the source code in order to create my P/Invoke API with helper classes for usability. 

```cpp
/*! Basic Pix */
struct Pix
{
    l_uint32             w;         /*!< width in pixels                   */
    l_uint32             h;         /*!< height in pixels                  */
    l_uint32             d;         /*!< depth in bits (bpp)               */
    l_uint32             spp;       /*!< number of samples per pixel       */
    l_uint32             wpl;       /*!< 32-bit words/line                 */
    l_uint32             refcount;  /*!< reference count (1 if no clones)  */
    l_int32              xres;      /*!< image res (ppi) in x direction    */
                                    /*!< (use 0 if unknown)                */
    l_int32              yres;      /*!< image res (ppi) in y direction    */
                                    /*!< (use 0 if unknown)                */
    l_int32              informat;  /*!< input file format, IFF_*          */
    l_int32              special;   /*!< special instructions for I/O, etc */
    char                *text;      /*!< text string associated with pix   */
    struct PixColormap  *colormap;  /*!< colormap (may be null)            */
    l_uint32            *data;      /*!< the image data                    */
};
typedef struct Pix PIX;
```

**Comment by fdncred** [comment]
I'm also confused about how the command line works and how the solution works. They seem to generate a different number of files.  These first two screenshots are from my solution. It's odd that there are files in the `netcoreapp2.2` folder and then there are files named `netcoreapp2.2;g-blah.cs`. The solution project generates 141 .cs files.
![lept1](https://user-images.githubusercontent.com/343840/51911302-191ee600-2397-11e9-89ae-9e996d200004.png)
![lept2](https://user-images.githubusercontent.com/343840/51911306-1c19d680-2397-11e9-9a75-0766b629a775.png)
This picture below is from the command line. With the command line I have 90 .cs files.
![commandline](https://user-images.githubusercontent.com/343840/51911390-4e2b3880-2397-11e9-981a-ae91e2fbe2c2.png)

**Comment by kaby76** [comment]
Got it. I just fixed this--using path separators instead of directory separators. On to fixing "-123123.cs" numbering issue then your .pig file.

**Comment by kaby76** [comment]
Thinking about this more carefully...

In C, there are struct/typedef, class/typedef, enum/typedef combinations:

struct Pix { ... }; typedef Pix PIX;

(1) The default is to generate two structs, one for "Pix", the other for the typedef PIX. In this case, C# gets "public struct Pix { ... }" and "public struct PIX { public Pix Value; }". (Note, the code should be robust enough to handle problems like what you point out "public struct PIX { public PIX Value; }").

(2) A second option is if you want to choose the typedef name or struct name. For example in this case, choose either (a) C# gets "public struct Pix { ... }" and all applied occurrences of PIX are just Pix; or (b) C# gets "public struct PIX { ... }" and all applied occurrences of Pix are PIX.

(3) A third option requires the user to write the struct by hand. In this case, the user wants to use either "Pix" or "PIX" as the name throughout the generated interface, but not generate a struct for either.

**Comment by fdncred** [comment]
I see your points. In my situation, I think I'd vote for 2a, but everyone may not choose as wisely as I do. ;) I definitely do not like 1. 3 is my fallback.

**Comment by kaby76** [comment]
I have a fix for this done, will release in the next hour or so. Please make sure to pick up the new .pig file (https://github.com/kaby76/PiggyLeptonica/blob/master/ConsoleApp1/lep.pig).

The fix involved clarifying the rewrite code for "applied occurrences" of C types. The problem is that Piggy doesn't have a good way to rewrite applied occurrence types, e.g., parameter types in function declarations, or fields in structure declarations. Those "ModParam...." functions were hacks to bypass the problem. I changed those functions to make a little more sense and renamed them. So your .pig file needed a changed. You can rewrite Pig to PIG or PIG to Pig, and it'll do the right thing in not generating the typedef struct.

-Ken

**Comment by kaby76** [comment]
Fix in v1.0.11. Version 1.0.10 had a problem with the templates with parameters.

**Comment by fdncred** [comment]
Hmm... I need to look at this closer because I have dozens of errors in g-functions.cs now. All the structs that are in capital letters are not found, but they exist.

Separately, maybe my pig is messed up too because what was previously converted to a string is now an IntPtr. Maybe I need to add all the defaults from ClangSupport.pig? Are these `ClangSupport.AddAppliedOccurrenceRewrites` meant to rewrite the defaults or add to them?

**Comment by fdncred** [comment]
I think these problems with g-functions.cs are just that all the .cs files are not added to the solution. Because these "errors" do not prevent the solution from building.

On the other item, I just added `{ "const char *", "string" },` to my pig file and I can pass a string like this again `var p = Functions.pixRead(feyn);` and get an IntPtr for return.

**Comment by kaby76** [comment]
The OutputPath wasn't observed, so that's probably why it couldn't find the files. Give it a try with v1.0.12.

As for the { "const char *", "string" }, that is expected. The reason is that I'm trying to follow the "standard" Microsoft lays out for pinvoke conversions. You will need to add that line now. But, this is a global switch for applied occurrences.

**Comment by fdncred** [comment]
It's mostly working like I think it should.
